language: java
jdk:
  - openjdk11

# 어느 브랜치가 푸시될 때 수행할 지 결정
branches:
  only: # master branch에 push될 때만 수행하라
    - master

# Travis CI Server Home
# gradle을 통해 의존성을 받으면 이를 해당 디렉토리에 캐싱, 동일한 의존성은 다음 배포때부터 다시 받지 않도록 한다
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master branch에 push되었을 때 수행되는 명령어
script: "./gradlew clean build"

# CI 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - 'eheh12321@gmail.com'